Fix undefined error when wrong arguments are passed
devinit/ddw-external-api pull request #32
Opened 2021-02-13 10:45 UTC by wakibi

Should be now able to gracefully return an error instead of breaking the whole application

2021-02-13 14:29 UTC, edwinmp requested changes
Finish it off with adding a `try & catch` block to surround the code in each route ... this is in the `src/routes/index.ts`. That should handle any & all unexpected errors gracefully.

2021-02-13 14:29 UTC, edwinmp commented on src/db.ts
> +    if (dc === null || dc === undefined) {
Write it as:
`if (!dc) {...}`

2021-02-13 14:29 UTC, edwinmp commented on src/db.ts
> +    if (schemas === null || schemas === undefined) {
Same here ...

2021-02-15 09:18 UTC, wakibi commented on src/db.ts
> +    if (schemas === null || schemas === undefined) {
c360959

2021-02-15 12:52 UTC, edwinmp approved these changes

2021-02-15 12:56 UTC, merged