refactor/strict code
devinit/ddw-external-api pull request #9
Opened 2019-01-17 09:00 UTC by edwinmp

2019-01-17 13:24 UTC, akmiller01 requested changes
Hey @edwinmp thanks for the refactor! I think I've just spotted one problem when deploying.

2019-01-17 13:24 UTC, akmiller01 commented on src/routes/index.ts
> +        res.status(200).sendFile(join(__dirname + '/index.html'));
@edwinmp Does this line work for you? When I deploy via docker locally I get `Error: ENOENT: no such file or directory, stat '/src/dist/routes/index.html'`

2019-01-17 13:42 UTC, edwinmp commented on src/routes/index.ts
> +        res.status(200).sendFile(join(__dirname + '/index.html'));
hmm... was fine locally. Let me look into it.

2019-01-17 13:45 UTC, akmiller01 commented on src/routes/index.ts
> +        res.status(200).sendFile(join(__dirname + '/index.html'));
I am using `docker-compose up` to deploy. Maybe I need to edit the `docker-compose.yml` to match something you're doing with docker?

2019-01-18 08:33 UTC, edwinmp commented on src/routes/index.ts
> +        res.status(200).sendFile(join(__dirname + '/index.html'));
This is fixed now. Merged in your fixes from the other branch as well, so I'm going to merge this into master.

2019-01-18 08:36 UTC, merged